"""
tests/test_report_agent_service.py
"""

from unittest.mock import patch

from services.report_agent_service import ReportService


def sample_data():

    return {
        "video_name": "video.mp4",
        "video_duration": "10:00",
        "video_resolution": "1920x1080",
        "video_fps": 30,
        "video_format": "MP4",
        "video_size": "100 MB",

        "audio_name": "audio.wav",
        "audio_duration": "10:00",
        "channels": 2,
        "sample_rate": 44100,
        "audio_format": "WAV",
        "audio_size": "20 MB",

        "transcript": "This is transcript.",

        "analysis": "This is AI analysis.",

        "chat": [
            {
                "user": "Hello",
                "assistant": "Hi"
            }
        ],

        "provider": "Ollama",
        "model": "qwen2.5",
    }


def test_timestamp():

    value = ReportService.timestamp()

    assert isinstance(value, str)

    assert len(value) >= 19


@patch(
    "services.report_agent_service.ReportService.timestamp"
)
def test_build_report(
    mock_timestamp,
):

    mock_timestamp.return_value = (
        "2026-01-01 10:00:00"
    )

    report = ReportService.build_report(
        sample_data()
    )

    assert "# 🎥 AI Video Analysis Report" in report

    assert "video.mp4" in report

    assert "10:00" in report

    assert "1920x1080" in report

    assert "This is transcript." in report

    assert "This is AI analysis." in report

    assert "Ollama" in report

    assert "qwen2.5" in report

    assert "Generated by AI Video Analysis Agent" in report


def test_build_report_defaults():

    report = ReportService.build_report({})

    assert "N/A" in report

    assert "Transcript not available." in report

    assert "Analysis not available." in report

    assert "[]" in report

    assert "Generated by AI Video Analysis Agent" in report


def test_chat_dict_conversion():

    data = sample_data()

    data["chat"] = {
        "user": "Hello",
        "assistant": "Hi",
    }

    report = ReportService.build_report(
        data
    )

    assert '"user"' in report

    assert '"assistant"' in report


def test_chat_list_conversion():

    data = sample_data()

    data["chat"] = [
        {
            "user": "A",
            "assistant": "B",
        }
    ]

    report = ReportService.build_report(
        data
    )

    assert '"user"' in report

    assert '"assistant"' in report


@patch(
    "services.report_agent_service.ReportService.build_report"
)
def test_generate_complete_report(
    mock_build,
):

    mock_build.return_value = (
        "Complete Report"
    )

    data = sample_data()

    result = ReportService.generate_complete_report(
        include_video=True,
        include_audio=True,
        include_transcript=True,
        include_analysis=True,
        include_chat=True,
        include_metadata=True,
        data=data,
    )

    assert result == "Complete Report"

    mock_build.assert_called_once_with(
        data
    )


def test_report_contains_sections():

    report = ReportService.build_report(
        sample_data()
    )

    assert "## 📹 Video Information" in report

    assert "## 🎵 Audio Information" in report

    assert "## 📝 Transcript" in report

    assert "## 🤖 AI Analysis" in report

    assert "## 💬 Chat History" in report

    assert "## ⚙ Metadata" in report

    assert "Generated by AI Video Analysis Agent" in report


def test_report_is_string():

    report = ReportService.build_report(
        sample_data()
    )

    assert isinstance(report, str)

    assert len(report) > 0